Task3 Calculator 1.1
ViktorDeinyi/Kh-067-QA-02autoJAVA pull request #5
Opened 2022-07-28 20:31 UTC by ViktorDeinyi

New changes: "switch" instead of "if-else"; checking the correctness of entering numbers.

2022-07-28 20:37 UTC, Hmeliumm requested changes

2022-07-28 20:37 UTC, Hmeliumm commented on Tasks/src/Calculator.java
> +        while (true) {
using while (true) - bad practice. Please change

2022-07-28 20:37 UTC, Hmeliumm commented on Tasks/src/Calculator.java
> +        while (true) {
using while (true) - bad practice. Please change

2022-08-03 06:25 UTC, ViktorDeinyi commented
> New changes: "switch" instead of "if-else"; checking the correctness of entering numbers, change (while - true) version 1.2

2022-08-09 10:01 UTC, Hmeliumm approved these changes

2022-08-09 10:01 UTC, merged